# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hoolai/WebKit-GIT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hoolai/WebKit-GIT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/Applications/CMake.app/Contents/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/Applications/CMake.app/Contents/bin/cpack --config ./CPackSourceConfig.cmake /Users/hoolai/WebKit-GIT/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hoolai/WebKit-GIT/CMakeFiles /Users/hoolai/WebKit-GIT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hoolai/WebKit-GIT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bmalloc

# Build rule for target.
bmalloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bmalloc
.PHONY : bmalloc

# fast build rule for target.
bmalloc/fast:
	$(MAKE) -f Source/bmalloc/CMakeFiles/bmalloc.dir/build.make Source/bmalloc/CMakeFiles/bmalloc.dir/build
.PHONY : bmalloc/fast

#=============================================================================
# Target rules for targets named WTF

# Build rule for target.
WTF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WTF
.PHONY : WTF

# fast build rule for target.
WTF/fast:
	$(MAKE) -f Source/WTF/wtf/CMakeFiles/WTF.dir/build.make Source/WTF/wtf/CMakeFiles/WTF.dir/build
.PHONY : WTF/fast

#=============================================================================
# Target rules for targets named JavaScriptCore

# Build rule for target.
JavaScriptCore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JavaScriptCore
.PHONY : JavaScriptCore

# fast build rule for target.
JavaScriptCore/fast:
	$(MAKE) -f Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/build.make Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/build
.PHONY : JavaScriptCore/fast

#=============================================================================
# Target rules for targets named LLIntOffsetsExtractor

# Build rule for target.
LLIntOffsetsExtractor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LLIntOffsetsExtractor
.PHONY : LLIntOffsetsExtractor

# fast build rule for target.
LLIntOffsetsExtractor/fast:
	$(MAKE) -f Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/build.make Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/build
.PHONY : LLIntOffsetsExtractor/fast

#=============================================================================
# Target rules for targets named jsc

# Build rule for target.
jsc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsc
.PHONY : jsc

# fast build rule for target.
jsc/fast:
	$(MAKE) -f Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/build.make Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/build
.PHONY : jsc/fast

#=============================================================================
# Target rules for targets named WebCore

# Build rule for target.
WebCore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WebCore
.PHONY : WebCore

# fast build rule for target.
WebCore/fast:
	$(MAKE) -f Source/WebCore/CMakeFiles/WebCore.dir/build.make Source/WebCore/CMakeFiles/WebCore.dir/build
.PHONY : WebCore/fast

#=============================================================================
# Target rules for targets named WebCoreTestSupport

# Build rule for target.
WebCoreTestSupport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WebCoreTestSupport
.PHONY : WebCoreTestSupport

# fast build rule for target.
WebCoreTestSupport/fast:
	$(MAKE) -f Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/build.make Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/build
.PHONY : WebCoreTestSupport/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... bmalloc"
	@echo "... WTF"
	@echo "... JavaScriptCore"
	@echo "... LLIntOffsetsExtractor"
	@echo "... jsc"
	@echo "... WebCore"
	@echo "... WebCoreTestSupport"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

